#include <iostream>

int main(int argc, char *argv[])
{
// Say hello to the world!
    std::cout << "Hello world, a skeleton app generated by appbuild." << std::endl;

// Display the constants defined by app build. 
    std::cout << "Build date and time " << APP_BUILD_DATE_TIME << std::endl;
    std::cout << "Build date " << APP_BUILD_DATE << std::endl;
    std::cout << "Build time " << APP_BUILD_TIME << std::endl;

// And quit
    return 0;
}

